### ISSUE TITLE
Publish release compatible with Coq 8.19

### ISSUE THREAD

**Issue by SnarkBoojum** [ott-lang/ott#105]
I'm sure you're already aware of that, but I prefer a ticket to be able to follow the situation ; the current version fails to compile with:
```
File "./ott_list_base.v", line 63, characters 57-66:
Error: The variable plus_comm was not found in the current environment.
```

**Comment by palmskog** [comment]
@SnarkBoojum in lieu of a release which will come later I patched the 0.33 release to support Coq 8.19: https://github.com/coq/opam/pull/3021

**Comment by SnarkBoojum** [comment]
Why not release 0.34 as 0.33+patch and later a 0.35 with new features ?

**Comment by palmskog** [comment]
The patch contains the smallest possible diff that makes the Coq library build, and was made specifically to enable Coq for 8.19 (following similar patches for similar Coq projects). Since the Coq library is only a small part of Ott, a new release would require many non-Coq-related steps that in my view would be a waste of (at this point, razor-thin) development resources, that could instead go towards a proper new release in the near future.

**Comment by palmskog** [comment]
See https://github.com/ott-lang/ott/releases/tag/0.34
